name: Project CI & merging to Staging
on:
  push:
    branches: development
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - 3.9
          - '3.10'
          - 3.11
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v3
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE: arkleap.settings
        run: pytest
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge development -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: stage
          message: Merge development into stage
          github_token: '${{ secrets.GITHUB_TOKEN }}'
