name: Creating PR on stage
on:
    workflow_run:
        workflows: 
          - CI-build
        types: 
          - completed
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: stage
      - name: Reset development branch
        run: |
          git fetch origin development:development
          git reset --hard development
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: stage-promotion