name: Auto-Merging
on:
  workflow_run:
    workflows: 
      - CI-build
    types: 
      - completed
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge development -> staging
        uses: devmasx/merge-branch@master
        with:
          # type: now
          from_branch: development
          target_branch: staging
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Merge staging -> uat
      #   uses: devmasx/merge-branch@master
      #   with:
      #     type: now
      #     from_branch: staging
      #     target_branch: uat
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
