name: Auto-Merging
on:
  workflow_run:
    workflows: 
      - CI-build123
    types: 
      - completed
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge development -> staging
        uses: devmasx/merge-branch@master
        with:
          # type: now
          from_branch: development
          target_branch: stage
          github_token: ${{ secrets.GITHUB_TOKEN }}
